steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dochelper-ai-server', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dochelper-ai-server']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dochelper-ai-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dochelper-ai-server'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'GROQ_API_KEY=${_GROQ_API_KEY}'
      - '--set-env-vars'
      - 'PRODUCTION_URL=${_PRODUCTION_URL}'

images:
  - 'gcr.io/$PROJECT_ID/dochelper-ai-server'